version: '3.1'
services:
  www:
    build: .
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - default
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sistema_financeiro
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default
volumes:
  db_data: